### PR TITLE
Review

### PR DESCRIPTION
**Pull request by digia3d**
Plain code

### CODE REVIEW

**Comment by sajjadrajaee** [comment]
Thank you for your commit.
Please add your modules to this project and other codes that are necessary to run your project. without that, I can't check your Javascript Best practice.
For example, please add items.js and AddTask.js.

**Comment by sajjadrajaee** [comment]
Wonderful work!
I saw your codes and they are clean and understandable and you followed Javascript best practices.

- [ ] Your code are clean
- [ ] You used DYR rule in your code
- [ ] You used KISS rule in your code
- [ ] Your used YAGNI rule in your code.
But there are some other suggestions that improve your coding:

- [ ] Please don't put your all codes inside `heading` tag. the purpose of `heading` tag is to assign headings inside it. you can use `article` tag instead.
- [ ] Your demo link doesn't work. It's better to fix it.

**Review by sajjadrajaee — APPROVED** [review]
Your code is Awesome.
Congratulations, it's time to merge it. 💯 🏆

**Comment by digia3d** [comment]
Thank you for the nice review. :smiley:

**Pull request merged**
